packaging_format = 2

id = "dagu"
name = "Dagu"
description.en = "Dagu is a powerful Cron alternative that comes with a Web UI. It allows you to define dependencies between commands as a Directed Acyclic Graph (DAG) in a declarative YAML Format."
description.fr = "Dagu is a powerful Cron alternative that comes with a Web UI. It allows you to define dependencies between commands as a Directed Acyclic Graph (DAG) in a declarative YAML Format."

version = "2.19.1~ynh1"

maintainers = ["pbrisacier@mncc.fr"]

[upstream]
# NB: Only the "license" key is mandatory. Remove entries for which there's no relevant data
license = "Zlib"
website = "https://dagu.readthedocs.io/"
admindoc = "https://dagu.readthedocs.io/"
userdoc = "https://dagu.readthedocs.io/"
code = "https://github.com/dagu-dev/dagu"

[integration]
yunohost = ">= 11.1.21"
architectures = "all"
multi_instance = false
ldap = false
sso = false
disk = "300M"
ram.build = "100M"
ram.runtime = "50M"

[install]
    [install.domain]
    # this is a generic question - ask strings are automatically handled by YunoHost's core
    type = "domain"

    [install.path]
    # this is a generic question - ask strings are automatically handled by YunoHost's core
    type = "path"
    default = "/dagu"

[resources]
    # See the packaging documentation for the full set
    # of explanation regarding the behavior and properties for each of those

    [resources.system_user]
    # This will provision/deprovision a unix system user

    [resources.data_dir]
    # This will create/remove the data dir as /home/yunohost.app/$app
    # and store the corresponding setting $data_dir
    subdirs = ["data"]

    [resources.permissions]
    # This will configure SSOwat permission for $domain/$path/
    # The initial allowed group of user is configured via the init_main_permission question (public=visitors, private=all_users)
    main.url = "/"
    main.auth_header = false

    [resources.ports]
    # This will pick a random port for reverse-proxying and store it as the $port setting

    [resources.apt]
    # This will automatically install/uninstall the following apt packages
    # and implicitly define the $phpversion setting as 8.0 (if phpX.Y-foobar dependencies are listed)
    packages = ["ca-certificates", "curl", "gnupg"]
    extras.docker.repo = "deb https://download.docker.com/linux/debian bullseye stable"
    extras.docker.key = "https://download.docker.com/linux/debian/gpg"
    extras.docker.packages = ["docker-ce", "docker-ce-cli", "containerd.io", "docker-buildx-plugin", "docker-compose-plugin"]
